### ISSUE TITLE
Does this addon work with cockpit master branch?

### ISSUE THREAD

**Issue by Reasno** [agentejo/CloudStorage#1]
Hi, 

I tried to install this addon with cockpit master branch but it didn't seem to work. I wonder if it is an error on my side.

**Comment by Reasno** [comment]
for future reference, the current master head is [1a5e5fa](https://github.com/agentejo/cockpit/commit/a83f7a6fde61c0f5ab1207dddc6978ec71a5e5fa)

**Comment by AwakenTheJaken** [comment]
Hey @Reasno! Have you had any luck with this? I'm attempting to do the same and after following the instructions there seems to be no change with how the files are being managed.

**Comment by aheinze** [comment]
Hi,

no this addon works only with the next branch for now. But it will get merged soon.

Greets,
Artur

**Comment by Reasno** [comment]
Thanks for letting us know! 
keep up the good work.
