### ISSUE TITLE
How to troubleshoot errors?

### ISSUE THREAD

**Issue by selfagency** [agentejo/CloudStorage#4]
I've configured this to work with Wasabi, which is an S3 compatible object storage service. However, whenever I attempt to upload an asset, it says "Something went wrong." There are no errors in either the console or php_error.log. Where can I find the error so I can figure out what the problem is?

**Comment by bartundmett** [comment]
The cloudstorage addon seems to not include an endpoint setting.

As long as its not provided, you can go into the addons/CloudStorage/bootstrap.php and add the correct endpoint to the Aws\S3\S3Client config.

This fixed it for me, using DO Spaces, should be the same for you.

If i get the time i will create a PR for this.

**Comment by selfagency** [comment]
Closed in favor of #5.
