### ISSUE TITLE
Unable to create symlink vendor/bin/jp.php: file name too long

### ISSUE THREAD

**Issue by gryphonmyers** [agentejo/CloudStorage#8]
When attempting to clone this repo, I get this error about a file name being too long. It appears there is a symlink in the repo, which seems a little strange. In any case, there would appear to be something broken about it - it's failing both for me locally (macOS Sierra) and in our Jenkins deployment (centos 7)

**Comment by gryphonmyers** [comment]
This is the file in question: https://github.com/agentejo/CloudStorage/blob/master/vendor/bin/jp.php

For this sort of thing - have we considered using git modules instead?

**Comment by aheinze** [comment]
can you please re-try again?

**Comment by gryphonmyers** [comment]
It's deploying now! Thanks @aheinze

**Comment by deronimo** [comment]
How was this issue resolved?
